"""Add column role in table Users and create postgres.Enum

Revision ID: 23d9080238b3
Revises: a0994ef3f1e6
Create Date: 2024-06-05 22:29:29.038975

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23d9080238b3'
down_revision: Union[str, None] = 'a0994ef3f1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ADMIN', 'MODERATOR', 'USER', name='userrole').create(op.get_bind())
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', 'MODERATOR', 'USER', name='userrole', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum('ADMIN', 'MODERATOR', 'USER', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
