"""Add stage Not Null in table Users column role

Revision ID: 805eb5c4240e
Revises: 23d9080238b3
Create Date: 2024-06-05 22:35:35.439902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '805eb5c4240e'
down_revision: Union[str, None] = '23d9080238b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MODERATOR', 'USER', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MODERATOR', 'USER', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
